key_access: "[INPUT ACCESS KEY HERE!!!]"
key_secret: "[INPUT SECRET KEY HERE!!!]"
coin_name: "KRW-BTC"
ma_line_1: 2
ma_line_2: 7
ma_line_3: 50
ma_check_sec: 10
loop_sec: 60
loop_check_sec: 120
discord_hook: "[DISCORD_HOOK URL HERE!!!]"
list_coin:
- name: "KRW-BTC"
  rate: 7000
  rate_profit: 0.0
  rate_stop_loss: 0.0
- name: "KRW-ETH"
  rate: 2000
  rate_profit: 0.0
  rate_stop_loss: 0.0
- name: "KRW-SOL"
  rate: 1000
  rate_profit: 0.0
  rate_stop_loss: 0.0