coin_name: "KRW-BTC"
ma_line_1: 2
ma_line_2: 7
ma_line_3: 50
ma_check_sec: 10
db_path: "/home/simple_msg.db"
polling_sec: 1
loop_sec: 60
loop_check_sec: 180
list_coin:
  - name: "KRW-BTC"
    rate: 3000
    rate_profit: 0.0
    rate_stop_loss: 0.0
    check:
      - "check_vb"
    check_count: 10
    is_sell_routine: false
  - name: "KRW-ETH"
    rate: 2000
    rate_profit: 0.0
    rate_stop_loss: 0.0
    check:
      - "check_ma"
      - "check_vb"
    check_count: 10
    is_sell_routine: true
  - name: "KRW-SOL"
    rate: 1000
    rate_profit: 0.0
    rate_stop_loss: 0.0
    check:
      - "check_ma"
      - "check_vb"
    check_count: 10
    is_sell_routine: true
  - name: "KRW-XRP"
    rate: 2000
    rate_profit: 0.0
    rate_stop_loss: 0.0
    check:
      - "check_ma"
      - "check_vb"
    check_count: 10
    is_sell_routine: true
  - name: "KRW-USDT"
    rate: 2000
    rate_profit: 2.0
    rate_stop_loss: 0.0
    check:
      - "check_exchange_rate"
    check_count: 0
    is_sell_routine: false
