coin_name: "KRW-BTC"
ma_line_1: 2
ma_line_2: 7
ma_line_3: 50
ma_check_sec: 10
db_path: "../simple_msg.db"
polling_sec: 1
loop_sec: 60
loop_check_sec: 180
list_coin:
  - name: "KRW-BTC"
    rate: 1000
    rate_profit: 3.0
    rate_stop_loss: 0.0
    is_repeat_buy_routine: false
    is_check_buy_count: true
    check_buy_count: 10
    check_buy:
      - module: "check_buy_ma"
        condition: "Optional"
      - module: "check_buy_vb"
        condition: "Required"
    check_sell:
      - module: "check_sell_time_ma20"
        condition: "Required"
      - module: "check_sell_profit"
        condition: "Required"
      - module: "check_sell_loss"
        condition: "Required"
  - name: "KRW-ETH"
    rate: 1000
    rate_profit: 3.0
    rate_stop_loss: 0.0
    is_repeat_buy_routine: false
    is_check_buy_count: true
    check_buy_count: 10
    check_buy:
      - module: "check_buy_ma"
        condition: "Optional"
      - module: "check_buy_vb"
        condition: "Required"
    check_sell:
      - module: "check_sell_time_ma20"
        condition: "Required"
      - module: "check_sell_profit"
        condition: "Required"
      - module: "check_sell_loss"
        condition: "Required"
  - name: "KRW-XRP"
    rate: 1000
    rate_profit: 3.0
    rate_stop_loss: 0.0
    is_repeat_buy_routine: false
    is_check_buy_count: true
    check_buy_count: 10
    check_buy:
      - module: "check_buy_ma"
        condition: "Optional"
      - module: "check_buy_vb"
        condition: "Required"
    check_sell:
      - module: "check_sell_time_ma20"
        condition: "Required"
      - module: "check_sell_profit"
        condition: "Required"
      - module: "check_sell_loss"
        condition: "Required"
  - name: "KRW-USDT"
    rate: 2000
    rate_profit: 3.0
    rate_stop_loss: 0.0
    is_repeat_buy_routine: true
    is_check_buy_count: false
    check_buy_count: 10
    check_buy:
      - module: "check_buy_exchange_rate"
        condition: "Required"
    check_sell:
      - module: "check_sell_profit"
        condition: "Required"
  - name: "KRW-SOL"
    rate: 1000
    rate_profit: 3.0
    rate_stop_loss: 0.0
    is_repeat_buy_routine: false
    is_check_buy_count: true
    check_buy_count: 10
    check_buy:
      - module: "check_buy_ma"
        condition: "Optional"
      - module: "check_buy_vb"
        condition: "Required"
    check_sell:
      - module: "check_sell_time_ma20"
        condition: "Required"
      - module: "check_sell_profit"
        condition: "Required"
      - module: "check_sell_loss"
        condition: "Required"
  - name: "KRW-DOGE"
    rate: 1000
    rate_profit: 3.0
    rate_stop_loss: 0.0
    is_repeat_buy_routine: false
    is_check_buy_count: true
    check_buy_count: 10
    check_buy:
      - module: "check_buy_ma"
        condition: "Optional"
      - module: "check_buy_vb"
        condition: "Required"
    check_sell:
      - module: "check_sell_time_ma20"
        condition: "Required"
      - module: "check_sell_profit"
        condition: "Required"
      - module: "check_sell_loss"
        condition: "Required"
  - name: "KRW-ADA"
    rate: 1000
    rate_profit: 3.0
    rate_stop_loss: 0.0
    is_repeat_buy_routine: false
    is_check_buy_count: true
    check_buy_count: 10
    check_buy:
      - module: "check_buy_ma"
        condition: "Optional"
      - module: "check_buy_vb"
        condition: "Required"
    check_sell:
      - module: "check_sell_time_ma20"
        condition: "Required"
      - module: "check_sell_profit"
        condition: "Required"
      - module: "check_sell_loss"
        condition: "Required"
  - name: "KRW-TRX"
    rate: 1000
    rate_profit: 3.0
    rate_stop_loss: 0.0
    is_repeat_buy_routine: false
    is_check_buy_count: true
    check_buy_count: 10
    check_buy:
      - module: "check_buy_ma"
        condition: "Optional"
      - module: "check_buy_vb"
        condition: "Required"
    check_sell:
      - module: "check_sell_time_ma20"
        condition: "Required"
      - module: "check_sell_profit"
        condition: "Required"
      - module: "check_sell_loss"
        condition: "Required"
