coin_name: "KRW-BTC"
ma_line_1: 2
ma_line_2: 7
ma_line_3: 50
ma_check_sec: 10
loop_sec: 60
loop_check_sec: 180
list_coin:
- name: "KRW-BTC"
  rate: 4000
  rate_profit: 0.0
  rate_stop_loss: 0.0
  check:
  - "check_ma"
  - "check_vb"
  check_count: 15
- name: "KRW-ETH"
  rate: 2000
  rate_profit: 0.0
  rate_stop_loss: 0.0
  check:
  - "check_ma"
  - "check_vb"
  check_count: 15
- name: "KRW-SOL"
  rate: 2000
  rate_profit: 0.0
  rate_stop_loss: 0.0
  check:
  - "check_ma"
  - "check_vb"
  check_count: 15
- name: "KRW-XRP"
  rate: 2000
  rate_profit: 0.0
  rate_stop_loss: 0.0
  check:
  - "check_ma"
  - "check_vb"
  check_count: 15